### ISSUE TITLE
Composed-task-runner restart results in exception DSL parse exception

### ISSUE THREAD

**Issue by PraneethPathireddy** [spring-cloud/spring-cloud-dataflow#3656]
Hello, I am using Dataflow server on kubernetes platform to to launch tasks. I am using composed-task-runner to launch composed-tasks. 

Data flow server version : 2.1.2.RELEASE
Composed-task-runner : 2.1.0.RELEASE

Composed-task : 

> StrDatTask-DownloaderTask && <StrDatTask-ItemTask || StrDatTask-ItemGrpTask || StrDatTask-PromoTask> && StrDatTask-DataPurgeTask

Whenever a composed-task-runner fails for any reason, I want to restart the composed task runner job via dashboard. But I am facing following exception in composed-task-runner 

```
org.springframework.cloud.dataflow.core.dsl.ParseException: 162E:(pos 128): unexpected data in task definition ','
StrDatTask-DownloaderTask && <StrDatTask-ItemTask || StrDatTask-ItemGrpTask || StrDatTask-PromoTask> && StrDatTask-DataPurgeTask, StrDatTask-DownloaderTask && <StrDatTask-ItemTask || StrDatTask-ItemGrpTask || StrDatTask-PromoTask> && StrDatTask-DataPurgeTask.

 at org.springframework.cloud.dataflow.core.dsl.AbstractTokenizer.raiseException(AbstractTokenizer.java:307) ~[spring-cloud-dataflow-core-2.0.0.RELEASE.jar:2.0.0.RELEASE]
        at org.springframework.cloud.dataflow.core.dsl.TaskTokenizer.process(TaskTokenizer.java:135) ~[spring-cloud-dataflow-core-2.0.0.RELEASE.jar:2.0.0.RELEASE]
        at org.springframework.cloud.dataflow.core.dsl.AbstractTokenizer.getTokens(AbstractTokenizer.java:99) ~[spring-cloud-dataflow-core-2.0.0.RELEASE.jar:2.0.0.RELEASE]
        at org.springframework.cloud.dataflow.core.dsl.TaskParser.<init>(TaskParser.java:65) ~[spring-cloud-dataflow-core-2.0.0.RELEASE.jar:2.0.0.RELEASE]
        at com.staples.rcp.mdf.composedtaskrunner.StepBeanDefinitionRegistrar.registerBeanDefinitions(StepBeanDefinitionRegistrar.java:56) ~[app/:na]
        at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.lambda$loadBeanDefinitionsFromRegistrars$1(ConfigurationClassBeanDefinitionReader.java:364) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684) ~[na:1.8.0_212]
        at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsFromRegistrars(ConfigurationClassBeanDefinitionReader.java:363) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:145) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:117) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:327) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:232) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:275) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:95) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:705) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:531) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) [spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) [spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
        at com.staples.rcp.mdf.composedtaskrunner.ComposedTaskRunner.main(ComposedTaskRunner.java:30) [app/:na]
```

As the above exception logs shows that in the composed task graph, the composed-task is repeated twice separated by comma.

**Comment by cppwfs** [comment]
Ok I'm still unable to reproduce the issue.  Here is what I did to match your description.
1. I created a small task application that will fail and registered it as "failapp"
2. I created a task definition`boo`  as follows: 
```
1: timestamp && <failapp || 2: timestamp || 3: timestamp> && 4: timestamp
```
3. I then launched the `boo` task definition with the following command line args:
```
--split-thread-core-pool-size=4 --interval-time-between-checks=1000
```
4.  The `boo` task launch failed as expected stating that `boo-failapp_0 returned a non-zero exit code`
5. I then relaunched `boo` using job restart option under jobs and the app launched and failed with the `boo-failapp_0 returned a non-zero exit code`
6. I then updated the failapp so that it would succeed.
7. I then relaunched `boo` using the play button on the task executions page.   And it completed successfully.

In the example above I was running on my local machine:
Data flow server version : 2.1.2.RELEASE
Composed-task-runner : 2.1.0.RELEASE

Are you passing in properties?
Also are you running on CF, Kubernetes, or Local?

**Comment by PraneethPathireddy** [comment]
> Ok I'm still unable to reproduce the issue. Here is what I did to match your description.
> 
> 1. I created a small task application that will fail and registered it as "failapp"
> 2. I created a task definition`boo`  as follows:
> 
> ```
> 1: timestamp && <failapp || 2: timestamp || 3: timestamp> && 4: timestamp
> ```
> 
> 1. I then launched the `boo` task definition with the following command line args:
> 
> ```
> --split-thread-core-pool-size=4 --interval-time-between-checks=1000
> ```
> 
> 1. The `boo` task launch failed as expected stating that `boo-failapp_0 returned a non-zero exit code`
> 2. I then relaunched `boo` using job restart option under jobs and the app launched and failed with the `boo-failapp_0 returned a non-zero exit code`
> 3. I then updated the failapp so that it would succeed.
> 4. I then relaunched `boo` using the play button on the task executions page.   And it completed successfully.
> 
> In the example above I was running on my local machine:
> Data flow server version : 2.1.2.RELEASE
> Composed-task-runner : 2.1.0.RELEASE
> 
> Are you passing in properties?
> Also are you running on CF, Kubernetes, or Local?

I am consistently getting this exception.  I am running on Kubernetes.

**Comment by cppwfs** [comment]
I was able to reproduce on Kubernetes.   Thanks for the additional information.

**Comment by jmenoud** [comment]
We have the same issue wenn restarting the a failed job (it seems that all parameters come double):
- I fixed this issue in a private fork of composed-task
- Then I got the error for the DB driver parameter. It was also set double

`org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Unsatisfied dependency expressed through method 'entityManagerFactory' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'entityManagerFactoryBuilder' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Unsatisfied dependency expressed through method 'entityManagerFactoryBuilder' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jpaVendorAdapter' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.orm.jpa.JpaVendorAdapter]: Factory method 'jpaVendorAdapter' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scopedTarget.dataSource' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Hikari.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.zaxxer.hikari.HikariDataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.IllegalStateException: Cannot load driver class: org.postgresql.Driver,org.postgresql.Driver`

**Comment by cppwfs** [comment]
Additional information: 
Assuming our batch job execution fails and we restart the job.
User restarts a failed job using the `exec` entry point.
The Data Flow code applies the command line args from the previous execution prior to sending it to the deployer.
The K8's deployer sees that the entry point is `exec` then reads the properties converts the properties to command line args.
So if I had a property foo=bar on "Run 1" the k8 deployer  with `exec` entry point will change it to  --foo=bar command line arg.
Now the command line arg now has --foo=bar --foo=bar .   So boot sees the property now as foo=bar,bar

Workaround: Use `boot` entry point.
Solution: When the K8 deployer is converting properties to command line args if using the `exec` entry point , it must check to make sure that the args doesn't already have that property enumerated already.   If so it will not add that property to the command line arg.   

I think we should close this issue and resolve it here: https://github.com/spring-cloud/spring-cloud-deployer-kubernetes/issues/345

**Comment by cppwfs** [comment]
Looks like this issue needs to be reopened.  We need to prevent the launch from resending command line args again.

**Comment by philippewanner** [comment]
I can confirm that it's still a problem on version 2.3.0.
We appreciate the reopening of this bug :) Thank you

**Comment by cppwfs** [comment]
In the 2.5.x we have resolved most of the issue.   However I did identify that on restart that a duplicate parentExecutionId is introduced by CTR on K8's .    This branch will resolve the issue: https://github.com/cppwfs/spring-cloud-dataflow/tree/SCDF-3656.  
  But have to wait for #3779 to be merged.
